# Generated by Django 5.2.12 on 2026-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер клубной карты'),
        ),
    ]
